export const GET_BEERS_SEARCH_TERM = 'GET_BEERS_SEARCH_TERM';
export const GET_BEERS = 'GET_BEERS';
export const GET_BEERS_NO_RESULTS = 'GET_BEERS_NO_RESULTS';
export const GET_BEERS_CHANGE_PAGE = 'GET_BEERS_CHANGE_PAGE';
export const GET_BEERS_HAS_MORE = 'GET_BEERS_HAS_MORE';
export const GET_BEERS_LOADING = 'GET_BEERS_LOADING';
export const GET_BEERS_ERROR = 'GET_BEERS_ERROR';
export const GET_BEERS_RESET = 'GET_BEERS_RESET';

export const FAVORITE_ADD = 'FAVORITE_ADD';
export const FAVORITE_REMOVE = 'FAVORITE_REMOVE';

export const SHOW_MODAL = 'SHOW_MODAL';
export const GET_SINGLE_BEER = 'GET_SINGLE_BEER';
export const LOADING_MODAL_DATA = 'LOADING_MODAL_DATA';